server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos12345

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(aLFaBK2uhEUJ9OboaRQHcx5zSEmj+K8jueUSYAuBYSTWqp7YL4Cpocd1wY0dVPwL0QMwKPtr70mUNKOr79CgYx/fiwidMsh46YVpeu6XPFiCAf9WNF6aXA==)
            client-secret: ENC(VBxAyv/8ryq1t50UTpYOb5wguzucQ7VP4DjuSQkjeic0aKZxbO8ZS1pnydiKKoww)
            scope:
              - email
              - profile
          facebook:
            client-id: ENC(lHTDfpahH04gDyVOnlEz9jZLrLVsDj9u)
            client-secret: ENC(/TfJWjMycHAPwxeHl7oVSWMGBmfjSgzkGGcfjX9FKPbZ1t4oxJ3OlpJJN2bFuDeZ)
            scope:
              - email
              - public_profile
          naver:
            client-id: ENC(GWDPJmLFU4kqhGvMoBOKT8KKqoxb3wZJKCR7Tw+AAN0=)
            client-secret: ENC(Rw7ECS8CiJi5qX0h/xe60y2CLY8wHiFX)
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json?? ??? response ?? ???? ???? ????.

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
